### ISSUE TITLE
Error while running and installation

### ISSUE THREAD

**Issue by Hemnathkumar** [drlukeparry/pyslm#1]
Hello sir,

I am trying to install PySLM module from Github. But i am facing some installation issues for which i am unable to find solutions through internet. 

When i tried to run the "example.py", i got this error "**module 'trimesh' has no attribute 'path'**". I have attached the screenshot of error too. Please helpmme out to resolve the issues.

Thanks in advance

Hemnath

![Pyslm error](https://user-images.githubusercontent.com/46291712/82233727-12cac980-994e-11ea-82f4-3b98f2ce0db6.JPG)

**Comment by drlukeparry** [comment]
You need to make sure that Trimesh package dependencies are installed: the error is usually typically occurs if RTree and Shapely python packages are not installed alongside trimesh.  

Let me know if you are stlil having this issue.

**Comment by Hemnathkumar** [comment]
Yes I have installed all the requirements as said in the requirements.txt

**Comment by Hemnathkumar** [comment]
![Pyslm requirements](https://user-images.githubusercontent.com/46291712/82236362-9d60f800-9951-11ea-8285-6d37df43d1bb.JPG)

**Comment by drlukeparry** [comment]
It sounds like an issue with trimesh - and shapely.  Can you try importing shapely and see if you get an error?

I am on gitter if you want to resolve it:

https://gitter.im/pyslm/community

**Comment by drlukeparry** [comment]
Issue closed - because this problem appears to be related to Trimesh.
