### ISSUE TITLE
Missing package 'Cython' when installing PythonSLM

### ISSUE THREAD

**Issue by Nevsden** [drlukeparry/pyslm#12]
I was installing the `PythonSLM` package as suggested in your readme. This means first I installed all required packages beforehand then installed `PythonSLM`. The installation did not finish as `Cython` was expected. Maybe you add it to your readme?

**Comment by drlukeparry** [comment]
Thank you for the suggestion.

 This has been added to the readme and also in the setup.py file, which will be update soon in v0.4
