### ISSUE TITLE
How do I transform layer geometries to machine build files

### ISSUE THREAD

**Issue by harshilpatel1799** [drlukeparry/pyslm#12]
Once I have a layers = []  defined or layer geometries completed.  How to I transform them to the slm file or machine build file?

**Comment by drlukeparry** [comment]
Please see the example for exporting to the Machine Build File. 

https://github.com/drlukeparry/pyslm/blob/dev/examples/example_exporting.py

You will need to install the libSLM package - which is currently under development - please send a query to dev (at) lukeparry.uk as you will need a compatible machine translator work with, which may not be available.
