### ISSUE TITLE
Error when try to replay the example: no module named'pyslm.visualise'

### ISSUE THREAD

**Issue by TomyTiger** [drlukeparry/pyslm#19]
import pyslm
import pyslm.visualise
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    import pyslm.visualise
ModuleNotFoundError: No module named 'pyslm.visualise'

Can you please help?

**Comment by drlukeparry** [comment]
This is unexpected behavior but it seems that you are using a different python executable (pyshell) ? Can you state which platform and python version you are using?

**Comment by TomyTiger** [comment]
I am using Python 3.10. Using IDLE to do the test.

**Comment by drlukeparry** [comment]
Hi TomyTiger,

I confirmed the behavior in some of the PySLM examples. The examples and PySLM has been correctly updated to import pyslm.visualise correctly (commit [d21a3159cd2dfee0d995692bff3b409ba11efe17](https://github.com/drlukeparry/pyslm/commit/d21a3159cd2dfee0d995692bff3b409ba11efe17)), which may resolve the issue in the upcoming release (0.5)
