### ISSUE TITLE
Index error:index 2 is out of bounds for axis 2 with size 2

### ISSUE THREAD

**Issue by TomyTiger** [drlukeparry/pyslm#20]
"""
A simple example showing how t use PySLM for generating a Stripe Scan Strategy across a single layer.
"""
import pyclipper
import sys 
sys.path.insert(0,r'C:\Program Files\Python\Python310\Lib\site-packages')
import numpy as np
import pyslm.pyslm
import pyslm.pyslm.analysis.utils as analysis
import pyslm.pyslm.hatching as hatching

# Imports the part and sets the geometry to  an STL file (frameGuide.stl)
solidPart = pyslm.pyslm.Part('cylinder')
solidPart.setGeometry(r'C:\Users\wdkxn9\Downloads\trimesh-main\trimesh-main\models\cylinder.stl')

"""
Transform the part:
Rotate the part 30 degrees about the Z-Axis - given in degrees
Translate by an offset of (5,10) and drop to the platform the z=0 Plate boundary
"""
solidPart.origin = [5.0, 10.0, 0.0]
solidPart.rotation = np.array([0, 0, 30])
solidPart.dropToPlatform()

print(solidPart.boundingBox)

# Set te slice layer position
z = 1.0

# Create a BasicIslandHatcher object for performing any hatching operations (
myHatcher = hatching.BasicIslandHatcher()
myHatcher.islandWidth = 3.0
myHatcher.stripeWidth = 5.0

# Set the base hatching parameters which are generated within Hatcher
myHatcher.hatchAngle = 10 # [°] The angle used for the islands
myHatcher.volumeOffsetHatch = 0.08 # [mm] Offset between internal and external boundary
myHatcher.spotCompensation = 0.06 # [mm] Additional offset to account for laser spot size
myHatcher.numInnerContours = 2
myHatcher.numOuterContours = 1
myHatcher.hatchSortMethod = hatching.AlternateSort()

"""
Perform the slicing. Return coords paths should be set so they are formatted internally.
This is internally performed using Trimesh to obtain a closed set of polygons.
The boundaries of the slice can be automatically simplified if desired. 
"""

geomSlice = solidPart.getVectorSlice(z, simplificationFactor=0.1)
layer = myHatcher.hatch(geomSlice)

**on above code, the error on line: layer = myHatcher.hatch(geomSlice)**

**Comment by drlukeparry** [comment]
Couldn't replicate the issue.
