### ISSUE TITLE
Hatch Order Issues

### ISSUE THREAD

**Issue by andenacitelli** [drlukeparry/pyslm#4]
Hello, 

I've been investigating using your library over the course of the last few weeks and am very impressed at what you've put together. 

However, I am a little confused by the output and hope you could clarify some things. I am slicing a pretty basic part and doing output like so: 

```python
# Create/wipe folder
if not os.path.exists("LayerFiles"):
    os.makedirs("LayerFiles")
else:
    for f in glob.glob("LayerFiles/*"):
        os.remove(f)

# Generate new output
for i in tqdm(range(len(layers)), desc="Generating Plots"):
    fig, ax = plt.subplots()
    PowderBedFusion.visualize.plot(
        layers[i], plot3D=False, plotOrderLine=False, plotHatches=True, plotContours=True, handle=(fig, ax))
    fig.savefig("LayerFiles/Layer{}.png".format(i), bbox_inches='tight')
    plt.cla()
    plt.close(fig)
```

Whenever I use the basic hatcher, I get the following for a layer:
![image](https://user-images.githubusercontent.com/30580900/114773373-fb9e8280-9d3c-11eb-8032-af27d5d1d316.png)

I would expect the colors to range from red to purple (or similar) across the entire part in a smooth progression. This seems to be the case for the top-right of the part, but this seems to fall apart drastically starting at the stripe just left of the maximum diagonal, and I can't really find any rhyme or reason as to why this occurs (edit: doesn't seem to occur for near-horizontal hatch directions).

Along a related vein, I have been experimenting with the implementation of island scanning that comes with the library. It gives me output like the following:
![image](https://user-images.githubusercontent.com/30580900/114773739-6a7bdb80-9d3d-11eb-8626-b73d235f7523.png)

While this doesn't look too bad, it seems like the top-right of the bottom few islands would be burned before the bottom-left of the respective islands; the color increment just looks like that would occur. That's not really a criminal issue, but leads up to something else I tried. 

I tried to modify the implementation of island scanning as follows to implement a random island order instead:

```python
# Went from this...
for i in np.arange(0, numIslands):
            for j in np.arange(0, numIslands):

# ---------------------------
# To this...
# Generate random order
island_order = np.empty((numIslands ** 2, 2), dtype=int)
idx = 0
for i in np.arange(0, numIslands):
    for j in np.arange(0, numIslands):
        island_order[idx] = np.array([i, j])
        idx += 1
np.random.shuffle(island_order)

# Iterate through islands and gen hatches
for island_coords in island_order:
    i, j = island_coords[0], island_coords[1]
```

This seems to be all well and good, and runs without crashing. However, I'm confused, because the output looks the same as your implementation of it: 
![image](https://user-images.githubusercontent.com/30580900/114774398-276e3800-9d3e-11eb-8e29-8df1f6e8fa49.png)

I've double-checked that the modified code is being run, that the values of i/j are set correctly, and that the output is regenerated from the modified code. Ideally the "heatmap" progression would jump from island to island at random, but unfortunately it seems like that's just top to bottom. 

Whether that's related to the first issue or not, I'm unsure. I'm hoping you can comment on if this is an issue with the library itself, the way you interface with `matplotlib`, or an issue with how I've hooked into `pyslm`. 

For reference, here is the part I'm testing with. GitHub didn't let me upload a raw .STL so I zipped it.
[Parameter_quality_nut_2.zip](https://github.com/drlukeparry/pyslm/files/6313555/Parameter_quality_nut_2.zip)

Thank you for your work and for your input! I'm hoping to potentially link this into a larger architecture with some real machines if pyslm ends up fitting my use case well, just currently trying to get my bearings with how the library works.

**Comment by drlukeparry** [comment]
Hi,

The order should be maintained across the part and in your case scan diagonally in one direction. To further visualise the scan vector order -  pass `plotOrderLine` as True, which shows the order of scanning via the midpoint of the hatch vectors.  If the `Hatcher` class is not working in the example, then there is clearly an underlying issue

Did you install the library from PyPi or clone the repo and use the library directly? I notice there is namespace change - did you use setup.py to compile the Python module you've adapted?

Until the first issue is resolved, I wouldn't expect that the random island scanning will work. In theory, your implementation should work correctly, as the vectors (including its ordering) within each island are added incrementally.

If you are happy to share a more complete script, I can perhaps understand if it is an error within the library or the installation and advise from there. 

All the best,
Luke

**Comment by andenacitelli** [comment]
Recloning and rebuilding the library was successful.

While a coworker _did_ do some namespace changes to make the library closer to a previous architecture we've been working with, I doubt that was the issue, as I suspect that would have just errored out at runtime due to import issues.

I suspect the issue was the second of your points; in the process of my coworker shifting over some stuff to what we were more familiar with, he ended up deleting some files that were pretty important - namely, that `setup.py` file, which I believe indicates the module wasn't being recompiled, or something similar. I'm not an expert on Python's exact compilation structure (particularly with respect to modules), and it's fixed, so it's good enough for me. 

The randomized version of island scanning is functional, if you're curious: 
![image](https://user-images.githubusercontent.com/30580900/114962359-89ab6380-9e38-11eb-9349-e66e5bf0e385.png)

I've gone ahead and essentially rolled back to using the vanilla version of the library. I'm not sure why we made any changes in the first place, but it's whatever, and we should be good now. Thank you for your help! I'll raise another issue if I run into anything else.
