### ISSUE TITLE
Sorting strategy `UnidirectionalSort` does not seem to return the hatching

### ISSUE THREAD

**Issue by Nevsden** [drlukeparry/pyslm#40]
I might be wrong, but I think here a simple return of the input hatching is missing?

https://github.com/drlukeparry/pyslm/blob/2046afedb881f7e800bdc0776374d56be64cb4b7/pyslm/hatching/sorting.py#L38

**Comment by Nevsden** [comment]
Also I want to thank you for your effort to make such a well-documented and concise library. Bravo!

**Comment by drlukeparry** [comment]
thank you for your nice comments.

The actual class is more of a placeholder - it does not actually modify the hatch vectors... It would be better if it can take a set of mis-orientated vectors and re-align them preferably in one direction but the situations were this occurs is very unlikely.

**Comment by Nevsden** [comment]
That does make sense hearing it from your perspective now. What bothers me a bit as a user of the api though is that the **hatch** function of the other Hatcher classes are inconsistent with the unidirectional class. That's why I wrote this issue in the first place.
