### ISSUE TITLE
Installing from PyPI failes as well as from github

### ISSUE THREAD

**Issue by p-o-seidon** [drlukeparry/pyslm#41]
I get this error with both kinds of installation, installing from PyPI and github. 

How have you worked around this?

----

Collecting PythonSLM
  Using cached PythonSLM-0.4.1.tar.gz (224 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      /usr/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-pa6iivme/pythonslm_fbae5b0882424dc7ba28284e7d2c049c/external/pyclipper/pyclipper.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      SCALING_FACTOR = 1
      
      
      def log_action(description):
          if not SILENT:
              print description
                    ^
      ------------------------------------------------------------
      
      external/pyclipper/pyclipper.pyx:20:14: Syntax error in simple statement list
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-pa6iivme/pythonslm_fbae5b0882424dc7ba28284e7d2c049c/setup.py", line 97, in <module>
          ext_modules=cythonize([ext, extB]),
                      ^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/usr/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: external/pyclipper/pyclipper.pyx
      Compiling external/pyclipper/pyclipper.pyx because it changed.
      [1/1] Cythonizing external/pyclipper/pyclipper.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by drlukeparry** [comment]
Two issues:

1) Version 0.4 is fairly much an out of date release, unless there are specific reasons for needing this. I will be releasing v0.6. in the coming month, which remove the need to use cython for compiling the polygon clipper library.
2) There is an issue and incompatibility between Python3.11 and cython when compiling the pyclipper module (which applies also to 0.5) 

What we have previously tried to get around this by reverting to an older cython version (0.29), which I suggest you try as a workaround.
