### ISSUE TITLE
libEGL warning DRI2 failed to authenticate

### ISSUE THREAD

**Issue by zhenhuashao** [drlukeparry/pyslm#45]
(base) oemSurface-Pro:~/qTdemo$ /usr/bin/python3 /home/oem/qTdemo/pyslm/examples/example 3d.py
Hatching started
Completed Hatching
libEGL warning: DRI2: failed to authenticate

**Comment by drlukeparry** [comment]
The error is likely related to the use visualisation and plotting of the scan vectors in 3D using matplotlib's backend.

 On Linux this will be related to the driver implementation and current backend (e.g. Qt5/Qt6) that is normally available, so is not likely to be related directly to PySLM in this instance.

**Comment by zhenhuashao** [comment]
谢谢
