### ISSUE TITLE
Manual Support Generation !

### ISSUE THREAD

**Issue by Vipul-M-Rawal** [drlukeparry/pyslm#47]
Sir, @drlukeparry, Can I generate support for a specific region instead of a complete overhang? I want to generate support on a particular patch, can I achieve this using the given code :
[https://github.com/drlukeparry/pyslm/blob/master/examples/example_support_structure.py](url)

**Comment by drlukeparry** [comment]
Yes it is possible to manually select/filter the Block Volume Support regions individually to obtain patches, which are generated  under `identifySupportRegions` like in the example on **line 85** in [example_support_structure.py](https://github.com/drlukeparry/pyslm/blob/master/examples/example_support_structure.py)

`
supportBlockRegions = supportGenerator.identifySupportRegions(myPart, OVERHANG_ANGLE, True)
`

The Support Generator class, can be used to produce a list of support volume objects for each identified region. These can be selected manually or algorithmically iterated across, as demonstrated additionally on **line 90**. This is relatively inexpensive to calculate compared to the more geometrically complex grid-truss support structures.

`
blockSupports = [block.supportVolume for block in supportBlockRegions]
`

If you are looking to create a specific region from an arbitrary projected shape generated by the user, this functionality is not yet implemented but could build on existing functionality already offered in the `pyslm.support.GridBlockSupport` class.
