### ISSUE TITLE
Debug Output in Release Version

### ISSUE THREAD

**Issue by andenacitelli** [drlukeparry/pyslm#5]
Hello, 

While testing a fresh install of the library, there seems to be a lot of what equates to debug output (ignore the "Processing Layers"; that's just tqdm):
![image](https://user-images.githubusercontent.com/30580900/114962816-6df48d00-9e39-11eb-9284-631bc98287c2.png)

Is this intentional, or is there a good reason for this? I'd think output like this isn't useful to the end user and would be better off deleted or optionally enabled. It's messing with my tqdm progress bars and I wanted to double-check if there is a specific reason why this is still around in the library, particularly on the master branch. Note that I built from source to achieve this result; I have no idea if the PyPi version would exhibit this behavior.

**Comment by andenacitelli** [comment]
I've opened a PR that (hopefully) addresses the issue: #6

**Comment by drlukeparry** [comment]
Yes, I am still become  learning to becoming more accustomed to formalizing the releases better and removing redundant debug information. I am not a fan of the python logging library. 

I will go through the pull request. Some information such as updating the geometry cache information, I would like to keep verbose to quickly identify issues. However, during the slicing/hatching, I think this debug output is safe to now remove. 

I will try and pull this into a maintenance release. 

Many thanks for your contribution,

Luke

**Comment by andenacitelli** [comment]
The pull request just comments out essentially all the output I could find. It's likely not the cleanest solution, as I agree some output from the library can be very useful in many use cases, so you are more than welcome to change it as you see fit. 

The cleanest way to do it, in my opinion (which is far from an expert one), would be some combination of the following:
- Tracking a boolean somewhere that toggles whether you want output from the library. This could be an optionally specified attribute in the `Part` class to control output for geometry-related options, and an optionally specified attribute in the `Hatcher` class (or similar) to control hatching-related output, so it's up to the end user whether they want the output. 
- Verbosity levels. For instance, fatal, error, warning, info, and debug, in declining order of importance. 

`tqdm` is a very solid way to track slicing and computation while the library is doing its magic, and output happening in the middle doesn't always mesh cleanly with that, so for my intended use case, the best solution would be one that allows me to stop all output that isn't a fatal error (warnings are also likely fine). 

Regardless, don't worry too much about tailoring it to my specific use case, as just working off of a fork is something I plan to do to some extent and is quite easy. However, I think a more in-depth and customizable way to get output from the library would be great to work towards for a future release.

**Comment by andenacitelli** [comment]
Seems to be fixed on dev. Nice!
