### ISSUE TITLE
Bug on class AlternateSort

### ISSUE THREAD

**Issue by ortmannrobert** [drlukeparry/pyslm#7]
Hi everyone,

Line 38 on pyslm/pyslm/hatching/sorting.py has a bug. It is not switching the direction of last vector if it has to be switched.

currently:` sv[1:-1:2] = np.flip(sv[1:-1:2], 1)`
suggested solution: `sv[1::2] = np.flip(sv[1::2], 1)
`
Kind regards
ortmannrobert

**Comment by drlukeparry** [comment]
Thank you for noticing that Ortmannrobert. 

I will make the suggested change, and hopefully push this  as a fix release soon.
